<a href="https://colab.research.google.com/github/barikbin/Generative-Adversarial-NN/blob/main/GAN_Intial_Model_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Generative Adversarial Neural Network - Prequisites - Stanford set 02

In [2]:

import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# this is a fee_dict with placeholder
# This is a placeholder for a vector of 3 elements, type tf.floar32

a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5,5,5], tf.float32)


Instructions for updating:
non-resource variables are not supported in the long term


In [6]:
c = a + b
writer = tf.summary.FileWriter('graph/placeholders', tf.get_default_graph())
with tf.Session() as sess:
   
  # compute the value of c given the value of a is [1, 2, 3] equals to [6. 7. 8.]
  # To get the result we need to run this syntax

  print(sess.run(c,{a: [1, 2, 3]}))

# Pay attention that we need to close the writer!
writer.close()

a = tf.add(2,5)
b = tf.multiply(a, 3)

with tf.Session() as sess:

  # we run the calculation two times here
  # 10 *
   print(sess.run(b))

# This is tricky syntax!  we multiply a three times.. a * 3b
   print(sess.run(b, feed_dict={a: 15}))

# need to redo the operand in tailwind css!


[6. 7. 8.]
21
45


In [11]:
!pip install tensorboard


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
# Different calculation
# Here we create simple log file writer

import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')
writer = tf.summary.FileWriter('./graphs/simple', tf.get_default_graph())

# This is an import syntax
with tf.compat.v1.Session() as sess:
    print(sess.run(x))
writer.close()


5


In [18]:

# Example number 2
a = tf.constant([2,2], name='a')

# Notice the shape of tensor
b = tf.constant([[0,1], [2,3]], name='b')

with tf.compat.v1.Session() as sess:
    print("First example")
    print(sess.run(tf.div(b,a)))
    print("Second example")
    print(sess.run(tf.math.divide(b,a)))
    print("Third example")
    print(sess.run(tf.math.truediv(b,a)))
    print("Fourth example")
    print(sess.run(tf.floordiv(b,a)))
    print("Fifth example")
    print(sess.run(tf.truncatediv(b, a)))
    print("sixth example")
    print(sess.run(tf.floor_div(b,a)))

First example
[[0 0]
 [1 1]]
Second example
[[0.  0.5]
 [1.  1.5]]
Third example
[[0.  0.5]
 [1.  1.5]]
Fourth example
[[0 0]
 [1 1]]
Fifth example
[[0 0]
 [1 1]]
sixth example
[[0 0]
 [1 1]]


In [20]:
 # calculation
 with tf.Session() as sess:
     print("First example")
     print(sess.run(tf.multiply(a,b)))
     print("Second example, the dot product")
     print(sess.run(tf.tensordot(a,b,1)))


First example
[[0 2]
 [4 6]]
Second example
[4 8]


In [25]:

t_0 = 19
x = tf.zeros_like(t_0)
y = tf.ones_like(t_0)

t_1 = ['apple', 'peach', 'banana']
x = tf.zeros_like(t_1)

t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]]

x = tf.zeros_like(t_2)  
y = tf.ones_like(t_2)

print(tf.int32.as_numpy_dtype())

my_const = tf.constant([1.0, 2.0], name='my_const')
print(tf.get_default_graph().as_graph_def())


0
node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\240@\000\000\240@\000\000\240@"
      }
    }
  }
}
node {
  name: "add"
  op: "AddV2"
  input: "Placeholder"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "add_1"
  op: "AddV2"
  input: "Placeholder"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "add_2"
  op: "AddV2"
  input: "Placeholder"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_FLOA